import * as cryptojs from "crypto-js";
export const environment = {
  production: false,
  key: cryptojs.enc.Utf8.parse('1234567890123456'),
  iv: cryptojs.enc.Utf8.parse('1234567890123456'),
  api_url: 'http://62.171.169.100:3010/parseur-awp/:',
  //api_url: 'https://gateway.drhsante.net:3010/endpoint-archivepro/:',
  CONFIG: {
    APP_NAME: 'ARCHIVE WEB PRO',
    API: '',
    APP_VERSION: '1.1',
    APP_CDN: '',
    APP_LOCAL_CDN: '',
    APP_API_URI: '',
    SRV_REST: 'api',
    PRODUIT: 'ARCHVAGE ELECTRONIQUE',
    SLOGAN: 'MIEUX GARDER POUR MIEUX SERVIR',
    APP_LOCALISATION: '',
    APP_TOKEN_NAME: '_v4_',
    layout_name: 'layout_version',
    APP_PASS: 'SàFçNMCëÎBAïÎNWiÏCA=',
    COPYRIGHT: 'Logiciel plus',
    LANG: 'fr',
    APP_ASSET: 'bng',
    APP_CONTACT: '07 09 75 08 95 / 07 09 46 41 23',
    APP_MAIL: 'gbangbojb@gmail.com',
    APP_SITE: '',
    APP_COUNTRY: 'Côte d\'Ivoire',
    APP_PAYS_CODE: 'ci',
    APP_PAYS_ISO: 'CIV',
  },
};
